import './style.css'

// import './lessons/pt1/lesson3-basic-scene'
// import './lessons/pt1/lesson5-transform-obj'
// import './lessons/pt1/lesson6-animation'
// import './lessons/pt1/lesson7-cameras'
// import './lessons/pt1/lesson8-resizing-canvas'
// import './lessons/pt1/lesson9-geometries'
// import './lessons/pt1/lesson10-debug-ui'
// import './lessons/pt1/lesson11-textures'
// import './lessons/pt1/lesson12-materials'
import './lessons/pt1/lesson13-3dtext'